name: 'Assume Role credentials'
description: 'Invokes stsAssumeRole and stores the AWS IAM crednetials in environment variables for follow-up steps'
branding:
  color: orange
  icon: cloud
inputs:
  role-arn:
    description: 'The ARN for an IAM role'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.role-arn }}
